http_port: 8080
base_host: "https://noname-1-a7233347.deta.app" 
#base_host: "http://localhost:8080"
db_connection_string: "sql12662095:SJbBnDL1w7@tcp(sql12.freemysqlhosting.net:3306)/sql12662095?parseTime=true"
gorm_debug: true
db_auto_migrate: true
cors:
  enabled: 1
  origins: "http://localhost:8000"
  allowed_methods: GET,POST
  exposed_headers:
  allowed_headers:
  debug: 0
  allow_credentials: 0
jwt:
  enabled: 1
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArFSW6d5J+OIAAo2zZqjXAoWB87chla1gOIHE9AnuflSJTXU5aHqqagOY3aLbKuZvGEdn0Xf41Be2bTEjB/TW4cAP5tRcatWaqgtcXNZDHHh8qQFvIslxyiTC5UFhxrs2bjGJE11pZSp+hgo49QLGWWAMi2VrKbaYm/yL+zNimctGdDSjilNq3n6U5K7kEQmC4A1TihW7L7FgPUwtQARL+hQ+8+NBRrW5o+fIeGqPqDbTVFaihePNvmRWjuuH+mkad9+X02kOrdF+O+2KAusiyd6DNWQbFr6gAZ9NCy9bXeswjlfOK6tozJQgc4v2lZt+83WQLFNGhVektHCcx0bqjwIDAQAB
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsVJbp3kn44gACjbNmqNcChYHztyGVrWA4gcT0Ce5+VIlNdTloeqpqA5jdotsq5m8YR2fRd/jUF7ZtMSMH9NbhwA/m1Fxq1ZqqC1xc1kMceHypAW8iyXHKJMLlQWHGuzZuMYkTXWllKn6GCjj1AsZZYAyLZWsptpib/Iv7M2KZy0Z0NKOKU2refpTkruQRCYLgDVOKFbsvsWA9TC1ABEv6FD7z40FGtbmj58h4ao+oNtNUVqKF482+ZFaO64f6aRp335fTaQ6t0X477YoC6yLJ3oM1ZBsWvqABn00LL1td6zCOV84rq2jMlCBzi/aVm37zdZAsU0aFV6S0cJzHRuqPAgMBAAECggEAY4r5IV4lnH3vQ4pWdpZQnERCLGU8IRlk2z8aZVzXRmHObc+ouZEhnts1EdFgiAdTZNLaRUTnlpub5LbdZVsoRH6MsOk5+Pwpus+VKosZePigCX+qko2KDRnu+j4qHIFHj59NbsImfylsrEB7ZguUR0wT8vFCVXYD8RaQRSoJaovsj33QB17mxPrU9Y60D93DTJ/O/eaO7jlz/MBsjdEC3t93ekPgB43MhwyBf9n5E924OBZOML7zn0z4iGeYHdWyqUGHjdkUcopzvKDJoCIEXDqBMVIs2BPxirhxSVZ4xGkQyvTdCMylTyyd62d+xaNWJ7KDmQPGbECDybITBtFuAQKBgQDrQklHcd5FMHiNxHm3pg9WT2XzCeOEv9Celjguoa4k3Gx+WXB6AGXF+8qWUwF3IvlMqRN/7YJ/bNCLsY+bVfOGL4NVD2k097FA5OLqQLJBirHBnp14Kpx/XecfLqkIr3SUeJDWlKUGsNey3AtxCyMBUaPq6ddBNievYjCQje13mQKBgQC7hgdHSUNHoM/4FVztBcxiYM8B8yy3RTDPIrhlGGbrSEUjwaXjHOL3oJZSTlcut0ptorl2gqa9jz88VGCuf8tgyWn/JSiElooEKazhianPTCqcEmzX3u16PNzHD1N0eW7kcX38lTpwoqXVhGwcf6Lu81e8jYZpZMfDDDSZzAmsZwKBgANzIGH00H6RPGNPyz0fKUBpv6P1tClhKqz4pPBCHKybsteTdivDz7o8e/cCVpYppCA0pn2MvQojTVePDf0IIJ8KGVHo/PDy5N1/vbgTpMmDQCIHsmVtsofHl7kEVSQ0dnAq6GzNFzJm63LK+Tv6HtRJHy81qJtjMOfId8/W1PGZAoGBAIFCzwuVdboPIKwaVbbQc2Uw5CCs9hrSp+VwQnj1TCRM6dPO7UFTLSSSXmwXskLyd2yBaaRGRRePgYBdjVNbpd5umBEXFQnoFvTtoUzKLvJEx25TyRE4iqvi/jB84QL9nbH8hWKxntn7U6KNqFQwqyhZNxYy2/8USBqr9Co7mkNrAoGAfLrTOqA9m54Gd+Lu3b/XR7arRUdVbOmAMull2JZdHNP6ZeJUCwiBjOZZoKI1oP8odl2aZR3JGcjzHGCVK5mb5oGonTu0/C7Y5JMLUzlrDjDNMh1Q/oXRwTJ0xzke0kPEGx/aXcR7DtOAygfrSpWnZYeYlwbMIeowbeR3zK6KXq4=
  expiry_time: -1
access_token_cookie:
  domain:
  cookie_name: jwt
  previous_domain:
secret_key: keynaykhongcoaibiethetne