definitions:
  authhandler.RefreshTokenResponse:
    type: object
  authhandler.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  authhandler.UserLoginResponse:
    type: object
  authhandler.UserRegistrationRequest:
    properties:
      display_name:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        maxLength: 12
        minLength: 9
        type: string
    required:
    - email
    - password
    - phone_number
    type: object
  authhandler.UserRegistrationResponse:
    properties:
      email:
        type: string
      message:
        description: WaitingResendOTPSeconds uint64 `json:"waiting_resend_otp_seconds"`
        type: string
      next_action:
        type: string
      phone_number:
        type: string
      session:
        type: string
    type: object
  authhandler.VerifyOTPRequest:
    type: object
  authhandler.VerifyOTPResponse:
    type: object
info:
  contact: {}
paths:
  /v1/public/auth/login:
    post:
      consumes:
      - application/json
      description: User login by phone or email
      parameters:
      - description: Request
        in: body
        name: UserLoginRequest
        required: true
        schema:
          $ref: '#/definitions/authhandler.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authhandler.UserLoginResponse'
      summary: User login by phone or email
      tags:
      - Public/Auth
  /v1/public/auth/refresh_token:
    get:
      consumes:
      - application/json
      description: Refresh Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authhandler.RefreshTokenResponse'
      summary: Refresh Token
      tags:
      - Public/Auth
  /v1/public/auth/registration:
    post:
      consumes:
      - application/json
      description: User registration by phone, email, display name
      parameters:
      - description: Request
        in: body
        name: UserRegistrationRequest
        required: true
        schema:
          $ref: '#/definitions/authhandler.UserRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authhandler.UserRegistrationResponse'
      summary: User registration by phone, email, display name
      tags:
      - Public/Auth
  /v1/public/auth/verify_otp:
    post:
      consumes:
      - application/json
      description: Verify OTP
      parameters:
      - description: Request
        in: body
        name: VerifyOTPRequest
        required: true
        schema:
          $ref: '#/definitions/authhandler.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authhandler.VerifyOTPResponse'
      summary: Verify OTP
      tags:
      - Public/Auth
  /v1/public/u/user/logout:
    post:
      consumes:
      - application/json
      description: Logout user
      produces:
      - application/json
      responses:
        "200":
          description: Logout ok!
          schema:
            type: string
      summary: Logout user
      tags:
      - Public/Auth
swagger: "2.0"
